# Site
name: "Blog da Enssure"
title: "Blog da Enssure"
description: "Blog sobre tecnologia e contribuição para a transformação digital de empresas de todos os tamanhos."
meta_description: "Blog sobre tecnologia e contribuição para a transformação digital de empresas de todos os tamanhos."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: ''
email: 'contato@enssure.com.br'
google_analytics: 'UA-164105821-1'
disqus: 'http-enssure-com-br-blog'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'
mailchimp: 'https://enssure.us4.list-manage.com/subscribe/post?u=681b9797a75aeffb641613a62&amp;id=0792a45135'
mailchimp_token: 'b_681b9797a75aeffb641613a62_0792a45135'

# Authors
authors:
  Celso:
    name: Celso
    display_name: Celso Inácio
    gravatar: "https://avatars2.githubusercontent.com/u/4915296?s=460&u=704524aba7f9120a17d1833f83b14a9a934814c9&v=4"
    email: celso@enssure.com.br
    web: https://github.com/ceelsoin
    twitter: https://www.linkedin.com/in/ceelsoinacio
    description: "Desenvolvedor e empreendedor Celso fundou a Enssure com desejo de tranformar digitalmente empresas de todos os tamanhos."
  Adriano:
    name: Adriano
    display_name: Adriano Laureano
    gravatar: "https://avatars0.githubusercontent.com/u/36384130?s=460&u=0517714a415420b28e629cafb664d132945513ae&v=4"
    email: adriano@enssure.com.br
    web: https://github.com/sl4ureano
    twitter: https://www.linkedin.com/in/slaureano/
    description: "Adriano é um desenvolvedor e empreendedor que no seu tempo livre adora contar histórias."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge